#log LEVEL
logging:
  level:
    root: INFO
  pattern:
    console: '%d{yyyy-M-d HH:mm:ss} %p [%file:%line] %t  %m%n'

#bigdata
hadoop:
  uri: 'hdfs://192.168.10.244:9000'
  appendFile: true

#NOSQL
spring:
  redis:
    database: 0
    host: 10.0.60.245
    port: 6379
    password: y4ELyfICoyY9UznE
    jedis:
      pool:
        max-active: 50
        min-idle: 10
        max-idle: 300
        max-wait: 10000ms
    timeout: 5000ms